spring:
  cloud:
    stream:
      default-binder: kafka
      kafka:
        binder:
          brokers:
            - localhost:9092
      bindings:
        input:
          binder: kafka
          destination: words
          content-type: text/plain
          group: input-group-1
        output:
          binder: kafka
          destination: words
          group: output-group-1
          content-type: application/json



#spring.cloud.stream.bindings:
#  words:
#    destination: words
#
#  count:
#    destination: words
#  kafka:
#    streams:
#      binder:
#        configuration:
#          commit.interval.ms: 100
#          default:
#            key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
#            value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
